apiVersion: akuity.io/v1alpha1
kind: NamespaceClassChangeRequest
metadata:
  name: internal-network-approval
spec:
  namespaceClassName: internal-network
  recommendationID: rec-xxx
  approved: true
  allowHighRisk: false
  # pullRequestURL: https://github.com/org/repo/pull/1
