apiVersion: akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  name: public-network
spec:
  resources:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-public-ingress
      spec:
        podSelector: {}
        policyTypes: ["Ingress"]
        ingress:
          - from:
              - ipBlock:
                  cidr: 0.0.0.0/0
---
apiVersion: akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  name: internal-network
  annotations:
    namespaceclass.akuity.io/switch-drift-mode: suggest-rollback-to-previous
spec:
  resources:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-vpn-only
      spec:
        podSelector: {}
        policyTypes: ["Ingress", "Egress"]
        ingress:
          - from:
              - ipBlock:
                  cidr: 10.10.0.0/16
        egress:
          - to:
              - ipBlock:
                  cidr: 10.10.0.0/16
